# Generated by Django 4.0 on 2023-12-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp3', '0004_myuser_first_name_myuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='mac_address',
            field=models.CharField(default=0, max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
