# Generated by Django 4.0 on 2023-12-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp3', '0006_myuser_personal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='public_key',
            field=models.TextField(blank=True),
        ),
    ]
