# Generated by Django 4.0 on 2023-12-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp3', '0008_remove_myuser_mac_address_remove_myuser_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
