# Generated by Django 4.0 on 2023-12-14 00:41

from django.db import migrations, models
import tp3.models


class Migration(migrations.Migration):

    dependencies = [
        ('tp3', '0009_myuser_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnauthorizedAccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=16)),
                ('password', models.BooleanField()),
                ('email_2fa', models.BooleanField()),
                ('face_id', models.BooleanField()),
                ('android_id', models.BooleanField()),
                ('last_photo', models.ImageField(upload_to=tp3.models.hacker_directory_path)),
            ],
        ),
    ]
