# Generated by Django 4.0 on 2023-12-14 00:45

from django.db import migrations, models
import tp3.models


class Migration(migrations.Migration):

    dependencies = [
        ('tp3', '0010_unauthorizedaccesshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthorizedaccesshistory',
            name='android_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unauthorizedaccesshistory',
            name='email_2fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unauthorizedaccesshistory',
            name='face_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unauthorizedaccesshistory',
            name='last_photo',
            field=models.ImageField(blank=True, null=True, upload_to=tp3.models.hacker_directory_path),
        ),
        migrations.AlterField(
            model_name='unauthorizedaccesshistory',
            name='password',
            field=models.BooleanField(default=False),
        ),
    ]
