# Generated by Django 4.0 on 2023-12-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp3', '0011_alter_unauthorizedaccesshistory_android_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unauthorizedaccesshistory',
            name='email',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tp3.myuser'),
            preserve_default=False,
        ),
    ]
