# Generated by Django 4.0 on 2023-12-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp3', '0012_unauthorizedaccesshistory_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unauthorizedaccesshistory',
            old_name='email',
            new_name='user',
        ),
    ]
