# Generated by Django 4.0 on 2023-12-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp3', '0013_rename_email_unauthorizedaccesshistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='android_id',
            field=models.CharField(default=None, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
