# Generated by Django 4.0 on 2023-12-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tp3', '0014_myuser_android_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedAccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tp3.myuser')),
            ],
        ),
    ]
